### ISSUE TITLE
naming?

### ISSUE THREAD

**Issue by matti** [bmw417/stack#1]
go get -d -v github.com/lossdev/stack
go: github.com/lossdev/stack upgrade => v1.0.2
go get: github.com/lossdev/stack@v1.0.2: parsing go.mod:
	module declares its path as: github.com/bmw417/stack
	        but was required as: github.com/lossdev/stack

**Comment by lossdev** [comment]
I can't reproduce your error as of yet. This error is showing up because I changed my username a few months back and had to redo go.mod to reflect that (see commit @f0e298c). 

As of 1.2, Travis CI and my own testing have seen no issues being able to pull the latest version of `stack`. This is my output in a fresh go container:

![image](https://user-images.githubusercontent.com/28501735/105603946-01df1d00-5d53-11eb-8187-49129336b149.png)

If all you did was `go get -d -v github.com/lossdev/stack`, then I'm not sure exactly what's going on here. What's your `go version` and what were the commands you used to try and download it (if there was anything extra / different than what you put above)?

**Comment by lossdev** [comment]
Update, I was able to reproduce this when I explicitly asked to download v1.0.2:

![image](https://user-images.githubusercontent.com/28501735/105611132-c9e6d280-5d70-11eb-8d3f-a0905a729c6f.png)

However, I was still unable to reproduce this without asking for that specific version - everywhere else I test `go get` it downloads `v1.0.1`, as that is the newest supported build and release in HEAD. 

I can try and go through the go package API and purge this old package so that this doesn't happen to anyone else - thanks for letting me know about it.

**Comment by matti** [comment]
yeah all I did was `go get -d -v github.com/lossdev/stack` and then I forked this and had similar error. Then I tagged a new version and installed that --> works

go mod is strange.

**Comment by lossdev** [comment]
Ok, what I think is going on is that an old version of the stack library under my old username was cached on the Go mirror servers as `v1.0.2`, conflicting with the current `v1.0.1` since the old version is a higher semantic number than the current. What I've done to circumvent this is make 2 new releases so that this repository is now up to `v1.0.3` - according to the mirror rules, `v1.0.3`'s existence will make `v1.0.2` not pull by default for anyone. 

I don't think I will ever be able to fix `v1.0.2`'s breakage ever - unless GitHub stops rewriting URLs for my old username to the new, `v1.0.2` will keep trying to download a module from an old repository that doesn't exist anymore. 

I've just "informed" the mirror server of `v1.0.3`'s existence, and those changes should propagate soon. Thanks again for bringing this up

**Comment by lossdev** [comment]
I've just tested the new version and it seems to have been resolved, so if you find anything else then comment again and we can look into reopening this
